import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

import AddBook from "./AddBook";
import NaurzieButton from "./NaurzieButton";
import SearchButton from "./Search";

export const metadata: Metadata = {
  title: "Naurzie",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return ( 
    <html lang="en">
      <ClerkProvider>
        <body>
          <div className="navbar bg-[#7e71bb] py-10">
            <div className="navbar-start">
              <NaurzieButton></NaurzieButton>
              <div className="pl-20">
                <AddBook></AddBook>
              </div>
              <div className="pl-8">
                <SearchButton></SearchButton>
              </div>
            </div>
            <div className="navbar-end">
              <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </div>
          {children}
        </body>
      </ClerkProvider>
    </html>

  );}

